### ISSUE TITLE
Error running cli

### ISSUE THREAD

**Issue by weiwarren** [cloudinary/cloudinary-cli#2]
python version 3.7.3 
cloudinary-cli 0.3.0

after successful installation using pip3, getting error when running cld
```
   File "/Library/Frameworks/Python.framework/Versions/3.7/bin/cld", line 6, in <module>
    from cloudinary_cli.cli import main
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cloudinary_cli/cli.py", line 11, in <module>
    from .modules import *
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cloudinary_cli/modules/__init__.py", line 1, in <module>
    from .make import make
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cloudinary_cli/modules/make.py", line 2, in <module>
    from cloudinary import uploader as _uploader, api, Search
ImportError: cannot import name 'Search' from 'cloudinary' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cloudinary/__init__.py)
```

**Comment by idobarnoam** [comment]
Thanks for bringing this to our attention @weiwarren.

 The current cli version is incompatible with the latest cloudinary package 1.18.1 which is the reason you are getting this error.

You could install the specific Cloudinary package that still supports cloudinary-cli which is 1.17.0 with the below command:
`pip3 install cloudinary==1.17.0`

The cloudinary-cli is a personal project of members of the cloudinary team and we would make efforts to have it compatible with the latest Cloudinary package.

Thanks!

**Comment by brian-cloudinary** [comment]
@weiwarren looks like there was an incompatible [change](https://github.com/cloudinary/pycloudinary/commit/56570ee625104853f47039c9dc8c5b514dd10d64#r35382148) in `cloudinary==1.18.0` that removed the `Search` class from the `cloudinary` module. I'm checking with the team whether this change was necessary. 

I added a hotfix for this in `0.3.1` so it can also be compatible with the latest cloudinary version.

Please run `pip3 install -U cloudinary-cli` to update the CLI.

Thanks!
