### ISSUE TITLE
Docker image containing cloudinary-cli

### ISSUE THREAD

**Issue by laurenskling** [cloudinary/cloudinary-cli#25]
# Feature request for Cloudinary CLI
…

## Explain your use case
I would love to see an official docker image containing an installed cloudinary-cli

## Describe the problem you’re trying to solve
I'm using cloudinary-cli in my gitlab pipelines, it requires me to install cloudinary-cli every run. If I'd be able to directly download an image with cloudinary-cli installed, I could skip installing it every time.

## Do you have a proposed solution?
The Dockerfile would be fairly simple  I guess.. 
```
FROM python:3.6
pip3 install cloudinary-cli
```
I guess thats enough.

**Comment by kurayami07734** [comment]
I would like to work on this

**Comment by gagandeepp** [comment]
https://github.com/cloudinary/cloudinary-cli/pull/96

**Comment by pataquets** [comment]
Size reduction:
* Use `--no-cache` `pip` switch
* Use `-slim` base image variant
Python version must be something more recent. 3.6 is way EOL'ed: https://endoflife.date/python

**Comment by gagandeepp** [comment]
@pataquets  I have fixed your pointers , please review
