### ISSUE TITLE
Sync subfolders

### ISSUE THREAD

**Issue by laurenskling** [cloudinary/cloudinary-cli#26]
# Feature request for Cloudinary CLI

I'd like to be able to sync all folders in one go. I can sync the root via `/` but this doesn't take (sub-)folders along with it.

## Explain your use case
`cld sync --pull ./bkp /` downloads all my media in the root, but not media in a folder. I'd like to get all folders as well.

## Describe the problem you’re trying to solve
trying to sync as completely as possible

## Do you have a proposed solution?
Sync all subfolders too :)

**Comment by const-cloudinary** [comment]
@laurenskling Thank you for reporting the issue! 
The fix is merged to master and will be released in the next version.

**Comment by laurenskling** [comment]
That's awesome! Thank you so much! <3

**Comment by laurenskling** [comment]
Just gave it a spin and works perfectly, thank you!
