### ISSUE TITLE
Error running migrate command

### ISSUE THREAD

**Issue by elenahongo** [cloudinary/cloudinary-cli#36]
## Describe the bug in a sentence or two.
I'm trying to run the migrate command 
`cld migrate -v -d ";" backgrounds images_to_upload.txt`
using a flat file with urls with this format:  https://upload.wikimedia.org/wikipedia/commons/4/4e/Hostel_International_San_Diego_Downtown_01.jpg separated with semicolons, getting this: `error: Command execution failed, error: Invalid URL 'h': No schema supplied. Perhaps you meant http://h?`

## Issue Type (Can be multiple)
- [ ] Build - Cannot install or import the SDK
- [ ] Performance - Performance issues
- [x] Behaviour - Functions are not working as expected (such as generate URL)
- [ ] Documentation - Inconsistency between the docs and behaviour
- [ ] Other (Specify)

## Steps to reproduce
1-To create a upload mapping to an existent folder
2-To create a flat file with urls, using semicolon as delimiter
3-To run this command - cld [cli options] migrate [command options] upload_mapping file

## Operating System
- [ ] Linux
- [x] Windows
- [x] macOS
- [ ] All

## Environment and Frameworks (fill in the version numbers)

- Cloudinary CLI version - 1.4.1,
- Cloudinary Python SDK version - 1.25.0
- Python Version - 3.9

**Comment by michalkcloudinay** [comment]
Hi @elenahongo, can you please open a ticket at: https://support.cloudinary.com/hc/en-us/requests/new, and provide your `txt` file so we can further take look? Thanks

**Comment by const-cloudinary** [comment]
Fixed in [1.4.2](https://github.com/cloudinary/cloudinary-cli/releases/tag/1.4.2)
