### ISSUE TITLE
Add support for signed urls

### ISSUE THREAD

**Issue by Qapybara28** [cloudinary/cloudinary-cli#60]
# Feature request for Cloudinary CLI

## Explain your use case
For security reasons (avoid path guessing), we need to protect the asset accesses with signed urls.

## Describe the problem you’re trying to solve
This feature is not supported by the cli currently (response from cloudinary support) 

## Do you have a proposed solution?
Implement or fix url signing logic from the SDK 

Related: https://github.com/cloudinary/cloudinary-cli/blob/5957d1aaff7fa1b6d5ac3c13d5861b97dd5da224/cloudinary_cli/utils/api_utils.py#L78

**Comment by IsraelArbus-cloudinary** [comment]
Hi Alexandre,

Thank you for reaching out.

I'm checking your inquiry with the team and will update you soon with our insights.

Warmest regards,
Israel

**Comment by wissam-khalili** [comment]
Hi @Qapybara28,

I would like to update you that we have pushed a fix today.
Please upgrade to the latest version (e.g. `pip install --upgrade cloudinary-cli `and run a `sync --pull` then it should work.
Please try it and let me know your feedback.

Thanks,
Wissam

**Comment by Qapybara28** [comment]
Thank you
