### ISSUE TITLE
Ability to upload contents of directory only without creating the parent directory in Cloudinary

### ISSUE THREAD

**Issue by chrissnyder2337** [cloudinary/cloudinary-cli#64]
# Feature request for Cloudinary CLI
Ability to upload contents of directory only without creating the parent directory in Cloudinary

## Explain your use case
It is impossible to use `cld upload_dir` to upload a local directory's contents to Cloudinary without also creating a directory/folder within Cloudinary that also has the same name.

## Describe the problem you’re trying to solve
Upload the contents of a local directory without creating the current directory as a folder in Cloudinary.

## Do you have a proposed solution?
Yes. Add an option to `cld upload_dir` to avoid creating the parent directory in Cloudinary.

**Comment by victorli-cloudinary** [comment]
Hi Chris,

Thanks for suggesting this for us! I've created a feature request for this which will be considered among other feature requests. If we have updates to share on this, we'll let you know.

**Comment by chrissnyder2337** [comment]
@victorli-cloudinary Thank you Victor!

I don't know if you saw, but I did open a PR that implements this change. From my testing, the functionality works. The only thing IMO that might need to be changed is the name of the command option I provided, `-c` (`--directory-contents-only`). _Naming things is hard_ 😄

**Comment by aleksandar-cloudinary** [comment]
Hi @chrissnyder2337, Thanks for opening that PR. I've tagged @const-cloudinary in the PR who will be able to review.
